name: readbook
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.3
  # 带缓存网络图片
  cached_network_image: ^3.3.0
  # 网络请求
  dio: ^5.4.0
  # 路由
  go_router: ^13.0.1

  flutter:
    sdk: flutter

    # iconfonts
  flutter_icons:
    git: https://github.com/jibiel/flutter-icons

  # 持久存储sp
  shared_preferences: ^2.1.1
  # 文件路径
  path: ^1.8.2
  path_provider: ^2.0.3
  # 权限
  permission_handler: ^10.2.0
  # 系统文件分享
  share_plus: ^4.0.4
  # NoSql数据库
  sembast: ^3.4.5
  sembast_web: ^2.1.3
  # xml转json
  xml2json: ^5.3.1
  # Google字体
  google_fonts: ^4.0.4
  # 日志打印管理
  logman: ^0.0.5
  # 状态管理
  flutter_riverpod: ^2.3.6
  # 状态管理2
  provider: ^6.1.1
  # Toast
  oktoast: ^3.4.0
  # WebView Android + IOS
  webview_flutter: ^4.4.4
  # 日志
  logger: ^2.0.2+1
  # 请求框架
  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.8.1

  iridium_reader_widget:
    path: ./packages/iridium/reader_widget

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  riverpod_generator: ^2.2.3
  retrofit_generator: '>=7.0.0 <8.0.0'
  json_serializable: ^6.6.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
